# Generated by Django 5.1.4 on 2026-03-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewapp', '0002_message_target_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
