# Generated by Django 5.1.4 on 2026-03-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lewapp', '0003_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
    ]
