# Generated by Django 5.1.4 on 2026-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewapp', '0006_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='accepted',
            field=models.BooleanField(default=None),
        ),
    ]
