# Generated by Django 5.1.4 on 2026-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewapp', '0007_alter_call_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
